<a href="https://colab.research.google.com/gist/JssanchezA/161784828538773966b31e9136ae997d/clase-1-08-032022.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Primner notbook

$$ax^2+bx+c=0$$

## Actividad:

$$\int \textit{u dv} \ = \textit{uv} \ - \int \textit{v du}$$

$$ \int u \ dv \ = \ uv \ - \int v \ du $$

In [ ]:
1+2

3

# Clase

$$ \begin{bmatrix}
A_1 & A_2 & A_3 \\
B_1 & B_2 & B_3 \\
C_1 & C_2 & C_3 \\
\end{bmatrix} $$

## Actividad:

\begin{bmatrix}
\beta _1 & \alpha _1 & \kappa _1 & \varepsilon _1 \\
\beta _2 & \alpha _2 & \kappa _2 & \varepsilon _2 \\
\beta _3 & \alpha _3 & \kappa _3 & \varepsilon _3 \\
\beta _4 & \alpha _4 & \kappa _4 & \varepsilon _4 \\
\end{bmatrix}

# Clase

![Python](https://th.bing.com/th/id/OIP.OWSpGf2FL9Jpee7t_AO41wHaFb?pid=ImgDet&rs=1)


## Actividad:

![texto del vínculo](https://content.invisioncic.com/r224567/monthly_2017_05/2000px-New-York-Yankees-Logo.svg.png.3efeeeda83d1ac6ec2ed4b71d9196eac.png)

\begin{array}{r l}
Jugador & Victorias \\
Mariano & 4 \\
Andrés & 10 \\
Fernando & 3
\end{array}

In [2]:
import pandas as pd

In [3]:
pd.read_excel("/content/sample_data/Parcial.xlsx")

,75000,1Ha,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13
0,0.5,diametro,NaN,NaN,78947,78947,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,0.95,germinación,NaN,NaN,NaN,0.126667,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,"0,9m",distancia entre surcos,NaN,NaN,NaN,0.140741,14.07414,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,11.160895,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,TIEMPOS (segundos),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,NaN,Gamma baja Caracol,Velocidad m/s,Gamma intermedia,Velocidad m/s,Gamma Alta Liebre,Velocidad m/s,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,1 cambio,46.36,2.027997,19.91,0.870954,9.04,0.395451,NaN,NaN,NaN,NaN,NaN,NaN,3600.000000
9,2 cambio,30.78,1.346457,13.23,0.57874,6.24,0.272966,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,3 cambio,23.09,1.010061,10.2,0.446194,4.81,0.210411,NaN,METROS,KILOMETROS,NaN,NaN,Tiempos horas,NaN
11,4 cambio,14.92,0.652668,6.68,0.292213,4.22,0.184602,NaN,22.86,0.2286,NaN,NaN,0.012878,0.005531
12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.00855,0.003675
13,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.006414,0.002833
14,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.004144,0.001856
15,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,NaN,NaN,NaN,NaN,TIEMPOS (segundos),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,NaN,NaN,NaN,NaN,Gamma baja Caracol,Velocidad m/s,Gamma intermedia,Velocidad m/s,Gamma Alta Liebre,Velocidad m/s,NaN,NaN,NaN,NaN
18,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,NaN,NaN,NaN,1 cambio,46.36,2.027997,19.91,0.870954,9.04,0.395451,NaN,NaN,NaN,NaN
20,NaN,NaN,NaN,2 cambio,30.78,1.346457,13.23,0.57874,6.24,0.272966,NaN,NaN,NaN,NaN
21,NaN,NaN,NaN,3 cambio,23.09,1.010061,10.2,0.446194,4.81,0.210411,NaN,NaN,NaN,NaN
22,NaN,NaN,NaN,4 cambio,14.92,0.652668,6.68,0.292213,4.22,0.184602,NaN,NaN,NaN,NaN

---

Subir archivo excel 

1. En el menu izquierdo abrir "files" 
2. Conectar el "drive"
3. Buscar el archivo dentro de "mi_drive"
4. Copiar el path